const hardwareQuestions = [
  {
    id: "C1-HW-Q001",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Easy",
    topic: "CPU",
    question: "Which component is responsible for processing instructions in a computer?",
    choices: ["RAM", "CPU", "SSD", "Power Supply"],
    answer: "CPU",
    explanation: "The CPU executes instructions and performs calculations for the system.",
    examTip: "Processing instructions = CPU.",
    memoryTrick: "CPU = Central Processing Unit.",
    commonMistake: "RAM stores active data, but it does not process instructions.",
    references: ["CompTIA A+ Core 1 Hardware"]
  },
  {
    id: "C1-HW-Q002",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Easy",
    topic: "RAM",
    question: "Which type of memory loses its contents when power is removed?",
    choices: ["RAM", "ROM", "SSD", "Flash memory"],
    answer: "RAM",
    explanation: "RAM is volatile memory, meaning it requires power to keep data.",
    examTip: "Volatile memory almost always means RAM.",
    memoryTrick: "RAM forgets when power is gone.",
    commonMistake: "Storage keeps data after shutdown. RAM does not.",
    references: ["CompTIA A+ Core 1 Memory"]
  },
  {
    id: "C1-HW-Q003",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Easy",
    topic: "Storage",
    question: "Which storage device has no moving parts and is usually faster than a traditional hard drive?",
    choices: ["HDD", "SSD", "Optical drive", "Tape drive"],
    answer: "SSD",
    explanation: "An SSD uses flash memory and has no spinning platters.",
    examTip: "No moving parts = SSD.",
    memoryTrick: "Solid state means no spinning disk.",
    commonMistake: "HDDs are storage too, but they use moving parts.",
    references: ["CompTIA A+ Core 1 Storage"]
  },
  {
    id: "C1-HW-Q004",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "Motherboards",
    question: "Before installing a new CPU, what should a technician verify first?",
    choices: ["Socket compatibility", "Monitor size", "Printer model", "Wi-Fi password"],
    answer: "Socket compatibility",
    explanation: "The CPU must match the motherboard socket and chipset support.",
    examTip: "CPU upgrades start with socket compatibility.",
    memoryTrick: "CPU must fit the socket.",
    commonMistake: "A faster CPU does not automatically work with every motherboard.",
    references: ["CompTIA A+ Core 1 Motherboards"]
  },
  {
    id: "C1-HW-Q005",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "Power Supply",
    question: "What does a desktop power supply primarily convert?",
    choices: ["AC to DC", "DC to AC", "HDMI to VGA", "IPv4 to IPv6"],
    answer: "AC to DC",
    explanation: "The power supply converts AC wall power into DC power used by internal components.",
    examTip: "Computer PSU = AC to DC.",
    memoryTrick: "Wall is AC. Components need DC.",
    commonMistake: "A surge protector protects power but does not convert it for the computer.",
    references: ["CompTIA A+ Core 1 Power"]
  },
  {
    id: "C1-HW-Q006",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "Power Connectors",
    question: "Which connector commonly provides supplemental power to the CPU?",
    choices: ["4-pin or 8-pin EPS", "SATA data", "RJ45", "HDMI"],
    answer: "4-pin or 8-pin EPS",
    explanation: "The EPS connector provides dedicated CPU power on many desktop motherboards.",
    examTip: "CPU power usually means EPS.",
    memoryTrick: "EPS feeds the processor.",
    commonMistake: "The 24-pin ATX connector powers the motherboard overall.",
    references: ["CompTIA A+ Core 1 Power Connectors"]
  },
  {
    id: "C1-HW-Q007",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "Storage Interfaces",
    question: "Which interface is commonly used by NVMe SSDs?",
    choices: ["PCIe", "IDE", "VGA", "RJ11"],
    answer: "PCIe",
    explanation: "NVMe SSDs use PCIe lanes for high-speed storage access.",
    examTip: "NVMe points to PCIe-based storage.",
    memoryTrick: "NVMe rides the PCIe highway.",
    commonMistake: "SATA SSDs are solid-state too, but NVMe is PCIe-based.",
    references: ["CompTIA A+ Core 1 Storage Interfaces"]
  },
  {
    id: "C1-HW-Q008",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Easy",
    topic: "Video Ports",
    question: "Which port commonly carries both video and audio?",
    choices: ["HDMI", "RJ45", "USB-A", "PS/2"],
    answer: "HDMI",
    explanation: "HDMI carries digital video and audio to monitors, TVs, and projectors.",
    examTip: "Video plus audio often points to HDMI or DisplayPort.",
    memoryTrick: "HDMI = High Definition Multimedia Interface.",
    commonMistake: "RJ45 is used for Ethernet networking.",
    references: ["CompTIA A+ Core 1 Ports"]
  },
  {
    id: "C1-HW-Q009",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Easy",
    topic: "Connectors",
    question: "Which connector is used for Ethernet cables?",
    choices: ["RJ45", "RJ11", "HDMI", "USB-C"],
    answer: "RJ45",
    explanation: "RJ45 connectors are used with Ethernet cables for wired networking.",
    examTip: "Ethernet connector = RJ45.",
    memoryTrick: "RJ45 has 8 pins.",
    commonMistake: "RJ11 is smaller and commonly used for telephone lines.",
    references: ["CompTIA A+ Core 1 Connectors"]
  },
  {
    id: "C1-HW-Q010",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "RAM Form Factors",
    question: "Which RAM form factor is commonly used in desktop computers?",
    choices: ["DIMM", "SODIMM", "NVMe", "M.2"],
    answer: "DIMM",
    explanation: "Desktop computers commonly use DIMM memory modules. Laptops commonly use SODIMM.",
    examTip: "Desktop RAM = DIMM. Laptop RAM = SODIMM.",
    memoryTrick: "SO-DIMM is the smaller one.",
    commonMistake: "NVMe and M.2 are storage-related, not desktop RAM form factors.",
    references: ["CompTIA A+ Core 1 Memory"]
  },
  {
    id: "C1-HW-Q011",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "Cooling",
    question: "A desktop shuts down shortly after booting and the CPU temperature is extremely high. Which component should be checked FIRST?",
    choices: ["CPU fan and heat sink", "Keyboard", "Ethernet cable", "Monitor cable"],
    answer: "CPU fan and heat sink",
    explanation: "High CPU temperatures usually point to a cooling issue. The technician should check that the CPU fan spins, the heat sink is seated properly, and thermal paste is applied correctly.",
    examTip: "Overheating questions usually point to fan, heat sink, airflow, or thermal paste.",
    memoryTrick: "Hot CPU? Fan, sink, paste.",
    commonMistake: "Do not troubleshoot the operating system first when the system is shutting down because of heat.",
    references: ["CompTIA A+ Core 1 Cooling"]
  },
  {
    id: "C1-HW-Q012",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "Thermal Paste",
    question: "What is the purpose of thermal paste between a CPU and a heat sink?",
    choices: ["Improve heat transfer", "Increase RAM speed", "Store BIOS settings", "Prevent malware"],
    answer: "Improve heat transfer",
    explanation: "Thermal paste fills tiny gaps between the CPU and heat sink so heat transfers more efficiently.",
    examTip: "Thermal paste supports cooling. It does not directly increase CPU speed.",
    memoryTrick: "Paste passes heat.",
    commonMistake: "Too much or too little thermal paste can cause cooling problems.",
    references: ["CompTIA A+ Core 1 Cooling"]
  },
  {
    id: "C1-HW-Q013",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "BIOS/UEFI",
    question: "Which firmware interface initializes hardware before the operating system loads?",
    choices: ["BIOS/UEFI", "NTFS", "DHCP", "HTTP"],
    answer: "BIOS/UEFI",
    explanation: "BIOS and UEFI initialize hardware during startup and then hand off control to the bootloader or operating system.",
    examTip: "Hardware initialization during startup = BIOS/UEFI.",
    memoryTrick: "BIOS/UEFI wakes the hardware up.",
    commonMistake: "NTFS is a file system, not firmware.",
    references: ["CompTIA A+ Core 1 Firmware"]
  },
  {
    id: "C1-HW-Q014",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "CMOS Battery",
    question: "A desktop keeps losing the correct date and time after being unplugged. Which component is MOST likely failing?",
    choices: ["CMOS battery", "CPU", "RAM", "SSD"],
    answer: "CMOS battery",
    explanation: "The CMOS battery helps preserve BIOS/UEFI settings, including date and time, when the computer is powered off.",
    examTip: "Clock resets after shutdown? Think CMOS battery.",
    memoryTrick: "CMOS keeps the clock alive.",
    commonMistake: "A dead CMOS battery does not usually erase files from storage.",
    references: ["CompTIA A+ Core 1 Motherboards"]
  },
  {
    id: "C1-HW-Q015",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "Expansion Cards",
    question: "Which expansion slot is commonly used for modern dedicated graphics cards?",
    choices: ["PCIe x16", "SATA", "M.2", "RJ45"],
    answer: "PCIe x16",
    explanation: "Dedicated graphics cards commonly use PCIe x16 slots because they provide high bandwidth.",
    examTip: "GPU slot = PCIe x16.",
    memoryTrick: "The big graphics card uses the big PCIe lane.",
    commonMistake: "M.2 is commonly used for SSDs and some wireless cards, not full-size graphics cards.",
    references: ["CompTIA A+ Core 1 Expansion Cards"]
  },
  {
    id: "C1-HW-Q016",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "RAID",
    question: "Which RAID level mirrors data across drives for redundancy?",
    choices: ["RAID 0", "RAID 1", "RAID 5", "JBOD"],
    answer: "RAID 1",
    explanation: "RAID 1 mirrors the same data across two drives. If one drive fails, the other still has the data.",
    examTip: "Mirror = RAID 1. Stripe = RAID 0.",
    memoryTrick: "RAID 1 looks like one drive reflected in a mirror.",
    commonMistake: "RAID 0 is faster but does not provide redundancy.",
    references: ["CompTIA A+ Core 1 RAID"]
  },
  {
    id: "C1-HW-Q017",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Medium",
    topic: "RAID",
    question: "Which RAID level stripes data for performance but provides no fault tolerance?",
    choices: ["RAID 0", "RAID 1", "RAID 5", "RAID 10"],
    answer: "RAID 0",
    explanation: "RAID 0 stripes data across drives to improve performance, but if one drive fails, the array fails.",
    examTip: "RAID 0 = speed, zero redundancy.",
    memoryTrick: "Zero safety in RAID 0.",
    commonMistake: "Do not choose RAID 0 when the question asks for fault tolerance.",
    references: ["CompTIA A+ Core 1 RAID"]
  },
  {
    id: "C1-HW-Q018",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Easy",
    topic: "Printers",
    question: "Which printer type uses toner and a fuser assembly?",
    choices: ["Laser", "Inkjet", "Thermal", "Impact"],
    answer: "Laser",
    explanation: "Laser printers use toner powder and a fuser assembly to bond toner to paper.",
    examTip: "Toner plus fuser = laser printer.",
    memoryTrick: "Laser locks toner with heat.",
    commonMistake: "Inkjet printers use liquid ink, not toner.",
    references: ["CompTIA A+ Core 1 Printers"]
  },
  {
    id: "C1-HW-Q019",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Easy",
    topic: "Printers",
    question: "Which printer type commonly uses liquid ink cartridges?",
    choices: ["Inkjet", "Laser", "Thermal", "Dot matrix"],
    answer: "Inkjet",
    explanation: "Inkjet printers spray liquid ink from cartridges onto paper.",
    examTip: "Liquid ink = inkjet.",
    memoryTrick: "Inkjet jets ink.",
    commonMistake: "Laser printers use toner powder, not liquid ink.",
    references: ["CompTIA A+ Core 1 Printers"]
  },
  {
    id: "C1-HW-Q020",
    core: "Core 1",
    domain: "Hardware",
    difficulty: "Easy",
    topic: "Laptop Memory",
    question: "Which memory form factor is commonly used in laptops?",
    choices: ["SODIMM", "DIMM", "PCIe x16", "ATX"],
    answer: "SODIMM",
    explanation: "SODIMM modules are smaller than standard DIMMs and are commonly used in laptops and compact systems.",
    examTip: "Laptop RAM = SODIMM.",
    memoryTrick: "SO-DIMM = Small Outline DIMM.",
    commonMistake: "DIMM is more common in desktop systems.",
    references: ["CompTIA A+ Core 1 Laptop Hardware"]
  },
  ,
{
  id: "C1-HW-0011",
  core: "Core 1",
  domain: "Hardware",
  difficulty: "Medium",
  topic: "Motherboards",
  question: "Which motherboard connector provides power directly to the CPU?",
  choices: [
    "24-pin ATX",
    "4/8-pin EPS",
    "SATA Power",
    "Molex"
  ],
  answer: "4/8-pin EPS",
  explanation: "The EPS connector supplies dedicated power to the processor.",
  examTip: "CPU power = EPS connector.",
  memoryTrick: "24-pin = motherboard. 8-pin = CPU.",
  commonMistake: "Don't confuse motherboard power with CPU power.",
  references: ["CompTIA A+ Core 1"]
},
{
  id: "C1-HW-0012",
  core: "Core 1",
  domain: "Hardware",
  difficulty: "Easy",
  topic: "Storage",
  question: "Which storage device typically provides the fastest boot times?",
  choices: [
    "HDD",
    "SSD",
    "Blu-ray",
    "Tape Drive"
  ],
  answer: "SSD",
  explanation: "Solid State Drives have no moving parts and offer much faster read/write speeds.",
  examTip: "Fast boot = SSD.",
  memoryTrick: "Solid State = Speed.",
  commonMistake: "Large capacity doesn't necessarily mean faster.",
  references: ["CompTIA A+ Core 1"]
},
{
  id: "C1-HW-0013",
  core: "Core 1",
  domain: "Hardware",
  difficulty: "Easy",
  topic: "Expansion Cards",
  question: "Which slot is commonly used for modern graphics cards?",
  choices: [
    "PCIe x16",
    "PCI",
    "AGP",
    "ISA"
  ],
  answer: "PCIe x16",
  explanation: "Modern GPUs use PCI Express x16 slots.",
  examTip: "Graphics = PCIe x16.",
  memoryTrick: "x16 = maximum speed.",
  commonMistake: "AGP is obsolete.",
  references: ["CompTIA A+ Core 1"]
},
{
  id: "C1-HW-0014",
  core: "Core 1",
  domain: "Hardware",
  difficulty: "Medium",
  topic: "Power Supplies",
  question: "What does PSU stand for?",
  choices: [
    "Primary System Unit",
    "Power Supply Unit",
    "Processor Support Utility",
    "Power System Utility"
  ],
  answer: "Power Supply Unit",
  explanation: "The PSU converts AC power into DC power used by the computer.",
  examTip: "PSU powers everything.",
  memoryTrick: "P = Power.",
  commonMistake: "The PSU does not process data.",
  references: ["CompTIA A+ Core 1"]
},
{
  id: "C1-HW-0015",
  core: "Core 1",
  domain: "Hardware",
  difficulty: "Medium",
  topic: "Cooling",
  question: "Which cooling solution generally provides better heat dissipation?",
  choices: [
    "Liquid Cooling",
    "Passive Cooling",
    "Heat Sink Only",
    "Dust Filter"
  ],
  answer: "Liquid Cooling",
  explanation: "Liquid cooling transfers heat more efficiently than standard air cooling.",
  examTip: "High-performance builds often use liquid cooling.",
  memoryTrick: "Water carries heat away.",
  commonMistake: "Passive cooling has no fans.",
  references: ["CompTIA A+ Core 1"]
},

  
];
